# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: railapp-api-migrate
#   labels:
#     app: railsapp
# spec:
#   template:
#     metadata:
#       labels:
#         app: railsapp
#     spec:
#       containers:
#       - command:
#         - rails
#         - db:migrate
#         envFrom:
#         - configMapRef:
#             name: rails-api
#         image: app:test1.1.1 #docker.io/geshan/band-api:latest
#         imagePullPolicy: Never #IfNotPresent
#         name: main
#       restartPolicy: Never
