{{- $values := .Values -}}
{{- $chart := .Chart -}}
{{- range .Values.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}
  labels:
    {{- toYaml .labels | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- toYaml .labels | nindent 8 }}
    spec:
      containers:
      - command:
        {{- toYaml .command | nindent 8 }}
        env:
        {{- range .env }}
          - name: {{ .name }}
            {{- if .value }}
            value: {{ .value }}
            {{- else }}
            valueFrom:
              secretKeyRef:
                name: {{ .secretName }}
                key: {{ .key }}
            {{- end }}
          {{- end }}
        envFrom:
          {{- range .envFrom }}
          - configMapRef:
              name: {{ .name }}
          {{- end }}
        image: "{{ $values.image.repository }}:{{ $values.image.tag | default $chart.AppVersion }}"
        imagePullPolicy: {{ $values.image.pullPolicy }}
        name: {{ .commandName }}
      restartPolicy: {{ .restartPolicy | default "Always" }}
---
{{- end }}
