apiVersion: apps/v1
kind: Deployment
metadata:
  name: railsapp-deployment
  namespace: ruby
spec:
  replicas: 3
  selector:
    matchLabels:
      app: railsapp
  template:
    metadata:
      labels:
        app: railsapp
    spec:
      containers:
      - name: railsapp
        image: bbilkevych/ruby-on-rails:main
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
        envFrom:
          - configMapRef:
              name: rails-api
