{{- range .Values.service_list }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    {{- toYaml .labels | nindent 4 }}
spec:
  {{- if .type }}
  type: {{ .type | default "ClusterIP" }}
  {{- end }}
  {{- if .port }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: http
  {{- end }}
  selector:
    {{- toYaml .labels | nindent 4 }}
---
{{- end }}
