#-----------------
# General Info
#-----------------
image:
  repository: bbilkevych/ruby-on-rails
  pullPolicy: Always
  tag: "feature-add-ci"

#-----------------
# HPA
#-----------------
autoscaling:
  enabled: false

#-----------------
# Deployments
#-----------------
deployments:
  - name: railsapp-deployment
    replicaCount: 3

    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%

    labels:
      app: railsapp

    podAnnotations: {}
    securityContext: {}
    imagePullSecrets: []

    env:
    - name: DATABASE_PASSWORD
      secretName: "postgres-ruby-creds"
      key: "Postgres_Password"

    envFrom:
    - configMapRef:
      name: rails-api

    service:
      targetPort: 3000

    livenessProbe:
      exec:
        command:
        - sh
        - "-c"
        - |
          ls
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        scheme: HTTP
        path: /
        port: 3000
      initialDelaySeconds: 5
      periodSeconds: 10

    resources:
      limits:
        cpu: 1
        memory: 256Mi
      requests:
        cpu: 0.5
        memory: 256Mi

#-----------------
# Services
#-----------------
service_list:
  - name: railsapp-service
    port: 80
    targetPort: 3000
    labels:
      app: railsapp

#-----------------
# Jobs
#-----------------
jobs:
  - name: railapp-api-migrate

    labels:
      app: railsapp

    command:
      - rails
      - db:migrate

    env:
      - name: DATABASE_PASSWORD
        secretName: "postgres-ruby-creds"
        key: "Postgres_Password"

    envFrom:
      - configMapRef:
        name: rails-api

    commandName: main

    restartPolicy: Never


#-----------------
# ConfigMap
#-----------------
configmap:
  - name: rails-api

    data:
      PORT: "3000"
      DATABASE_NAME: "postgres"
      DATABASE_USER: "postgres"
      DATABASE_HOST: "postgres-postgresql.database.svc.cluster.local"
      DATABASE_PORT: "5432"
